networks:
  all:
    driver: bridge
  
services:
  aws:
   build:
     context: .
     dockerfile: docker/aws/Dockerfile
   env_file:
     - .env.aws
   ports:
      - 8001:8080
   networks:
      - all

  postgresql:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - all

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./minio:/data
    networks:
      - all
    command: server --address ":9000" --console-address ":9001" /data
   