[tool.poetry]
name = "linguaweb_api"
version = "0.1.0"
description = "A beautiful description."
authors = ["Reinder Vos de Wael <reinder.vosdewael@childmind.org>"]
license = ""
readme = "README.md"
packages = [{include = "linguaweb_api", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.108.0"
pydantic-settings = "^2.1.0"
uvicorn = "^0.25.0"
sqlalchemy = "^2.0.25"
openai = "^1.11.1"
psycopg2-binary = "^2.9.9"
boto3 = "^1.34.38"
python-multipart = "^0.0.6"
ffmpeg-python = "^0.2.0"
pyyaml = "^6.0.1"
pytest-dotenv = "^0.5.2"
mangum = "^0.17.0"
instructor = "^0.5.2"
cloai = "^0.0.1a10"
ruff = "^0.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
mypy = "^1.8.0"
pre-commit = "^3.6.0"
pytest-cov = "^4.1.0"
httpx = "^0.26.0"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.23.3"
moto = {extras = ["all"], version = "^4.2.14"}
types-pyyaml = "^6.0.12.12"
types-requests = "^2.31.0.20240125"

[tool.poetry.group.docs.dependencies]
pdoc = "^14.4.0"

[tool.poetry.extras]
docs = ["pdoc"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
env_files = [
  "./tests/.test.env"
]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv"
]
line-length = 88
indent-width = 4
src = ["src"]
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN101",  # Self should never be type annotated.
  "ANN102",  # cls should never be type annotated.
  "B008"  # Allow function call in arguments; this is common in FastAPI.
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/**/*.py" = [
  "S101",  # Allow assets
  "ARG",  # Unused arguments are common in tests (fixtures).
  "FBT",  # Allow positional booleans
  "SLF001",  # Allow private member access.
  "INP001"  # No need for namespace packages in tests.
]
"src/**/models.py" = [
  "A003"  # Allow id as a field name.
]
"src/**/schemas.py" = [
  "A003"  # Allow id as a field name.
]

[tool.vulture]
make_whitelist = true
min_confidence = 80
paths = ["src"]
sort_by_size = true
verbose = false

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
